#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  activemq:
    ##http://activemq.apache.org/failover-transport-reference.html
    ##failover:tcp://host1:port1,tcp://host2:port2
    broker-url: ""
    user: ""
    password: ""
    packages:
      #trusted: java.time,java.lang,com.dotori.example.amazonmq
      trust-all: true
    pool:
      block-if-full: true # 익명의 "MessageProducer"인스턴스 만 사용할지 여부. false를 설정하면 (자), 항상 「MessageProducer」를 작성할 필요가 있습니다.
      block-if-full-timeout: -1ms # 풀이 아직 채워져 있으면 예외를 throw하기 전에 차단 기간.
      create-connection-on-startup: true # 시작할 때 연결을 만들지 여부. 시작시 풀을 예열하는 데 사용할 수 있습니다.
      enabled: false # 일반 ConnectionFactory 대신 PooledConnectionFactory를 작성해야하는지 여부.
      expiry-timeout: 0ms # 연결 만료 시간 초과.
      idle-timeout: 30s # 연결 유휴 시간 초과.
      max-connections: 1 # 풀링 된 최대 연결 수입니다.
      maximum-active-session-per-connection: 500 # 연결 당 활성 세션의 최대 수.
      reconnect-on-exception: true # "JMSException"이 발생할 때 연결을 재설정하십시오.
      time-between-expiration-check: -1ms # 유휴 연결 퇴출 스레드가 실행되는 사이에 잠자기 시간. 음수 인 경우 유휴 연결 퇴거 스레드는 실행되지 않습니다.
      use-anonymous-producers: true # 익명의 "MessageProducer"인스턴스 만 사용할지 여부. false를 설정하면 (자), 항상 「MessageProducer」를 작성할 필요가 있습니다.


server:
  port: 8091

debug: true

---
spring:
  profiles: local-8091
server:
  port: 8091

---
spring:
  profiles: local-8092
server:
  port: 8092